language: node_js
node_js:
  - "stable"
env:
  global:
  - CC_TEST_REPORTER_ID=d3550e58da3806584d3a9a5c48d8668838b3a9568e446bc288ef776124039ea4
cache:
  directories:
    - "node_modules"

install:
  - npm install

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script:
  - npm run test
  
after_success:
  - npm run coverage
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
